SET SQL_SAFE_UPDATES = 0;
UPDATE TOP_SPOTIFY SET TITULO = UPPER(TITULO), ARTISTA = UPPER(ARTISTA);

ALTER TABLE TOP_SPOTIFY ADD PERMANENCIA INT;
UPDATE TOP_SPOTIFY SET PERMANENCIA = YEAR(CURDATE()) - ANO;

CREATE TABLE ULTIMOS_LANZAMIENTOS
SELECT * FROM TOP_SPOTIFY
WHERE PERMANENCIA < 4;
DELETE FROM TOP_SPOTIFY
WHERE PERMANENCIA < 4;

INSERT INTO TOP_SPOTIFY
VALUES (3, 'CAN YOU FEEL MY HEART', 'BMTH', 'ROCK', 2012, 3);

INSERT INTO ULTIMOS_LANZAMIENTOS (ID, TITULO, ARTISTA, GENERO,
ANO, PERMANENCIA)
SELECT ID, TITULO, ARTISTA, GENERO, ANO, PERMANENCIA
FROM TOP_SPOTIFY
WHERE PERMANENCIA < 4;
DELETE FROM TOP_SPOTIFY
WHERE PERMANENCIA < 4;